version: '3.9'

services:
  api:
    build:
      context: ./src/FileProcessing.API
      dockerfile: Dockerfile
    container_name: fileprocessing_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - seq
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      # PostgreSQL 
      ConnectionStrings__Default: "Host=postgres;Port=5432;Username=fileprocessuser;Password=fileprocesspass;Database=fileprocessdb"

      # RabbitMQ
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__ConnectionString: "amqp://guest:guest@rabbitmq:5672/"
      RabbitMQ__Queue: upload_queue

      # Seq
      Seq__Url: "http://seq:5341"

    volumes:
      - ./uploads:/app/uploads

  worker:
    build:
      context: ./src/FileProcessing.Worker
      dockerfile: Dockerfile
    container_name: fileprocessing_worker
    depends_on:
      - postgres
      - rabbitmq
      - seq
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__Default: "Host=postgres;Port=5432;Username=fileprocessuser;Password=fileprocesspass;Database=fileprocessdb"

      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__ConnectionString: "amqp://guest:guest@rabbitmq:5672/"
      RabbitMQ__Queue: upload_queue

      Seq__Url: "http://seq:5341"

    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:16
    container_name: fileprocessing_postgres
    restart: always
    environment:
      POSTGRES_USER: fileprocessuser
      POSTGRES_PASSWORD: fileprocesspass
      POSTGRES_DB: fileprocessdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fileprocessuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fileprocessing_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:latest
    container_name: fileprocessing_seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data

volumes:
  postgres_data:
  seq_data:
