version: '3.9'

services:

  api:
    build:
      context: ./src
      dockerfile: FileProcessing.API/Dockerfile
    container_name: fileprocessing_api
    depends_on:
      - postgres
      - rabbitmq
      - seq
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      # PostgreSQL
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=filesdb;Username=postgres;Password=fileprocesspass"

      # RabbitMQ
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__ConnectionString: "amqp://guest:guest@rabbitmq:5672/"
      RabbitMQ__Queue: upload_queue

      # Seq
      Seq__Url: "http://seq:80"
      
      Storage__Local__BasePath: "/app/uploads"

    volumes:
      - ./uploads:/app/uploads
      - ./docker/init/03-create-log-folders.sh:/docker-entrypoint-initdb.d
  worker:
    build:
      context: ./src
      dockerfile: FileProcessing.Worker/Dockerfile
    container_name: fileprocessing_worker
    depends_on:
      - postgres
      - rabbitmq
      - seq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=filesdb;Username=postgres;Password=fileprocesspass"

      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest
      RabbitMQ__ConnectionString: "amqp://guest:guest@rabbitmq:5672/"
      RabbitMQ__Queue: upload_queue

      Seq__Url: "http://seq:80"
      
      Storage__Local__BasePath: "/app/uploads"
      
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fileprocesspass
      POSTGRES_DB: filesdb
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fileprocessing_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
      

volumes:
  postgres_data:
  seq_data:
